data_ingestion:
  root_dir: 'path_to_root_directory'
  source_url: 'url_to_data_source'
  local_data_file: 'path_to_local_data_file'
  unzip_dir: 'path_to_unzip_directory'

google_drive:
  credentials_info:
    type: 'service_account'
    project_id: 'deductive-smile-428006-v6'
    private_key_id: '32a3c7953f0950e519291cc251ba24b94617187c'
    private_key: '-----BEGIN PRIVATE KEY-----\n...'
    client_email: 'drive-api@deductive-smile-428006-v6.iam.gserviceaccount.com'
    client_id: '110633217942673347222'
    auth_uri: 'https://accounts.google.com/o/oauth2/auth'
    token_uri: 'https://oauth2.googleapis.com/token'
    auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs'
    client_x509_cert_url: 'https://www.googleapis.com/robot/v1/metadata/x509/drive-api@deductive-smile-428006-v6.iam.gserviceaccount.com'
    universe_domain: 'googleapis.com'

main_folder_id: '1RFTdV4WCu9o489_I4tkELAiRjEssCl2Q'
