artifacts_root : artifacts

data_ingestion :
  root_dir: artifacts/data_ingestion
  sourcs_url : https://drive.google.com/drive/folders/1nmKvlW0qys9Q4isc83hDY50qUN9fJEmw
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_data: artifacts/data_ingestion
